# Generated by Django 3.2 on 2021-04-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('catalog', '0003_alter_product_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='channels',
            field=models.ManyToManyField(to='channel.Channel'),
        ),
    ]
